namespace ServiceManagement_DOM_Link_ConfigurationVersions_To_Services
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by the Dom Editor automation script.
	//     Changes to this file will be lost if the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------
	namespace DomIds
	{
		using System;

		using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
		using Skyline.DataMiner.Net.Sections;

		public static class SlcServicemanagement
		{
			public const string ModuleId = "(slc)servicemanagement";
			public static class Enums
			{
				public static class Serviceitemtypes
				{
					public const string Workflow = "Workflow";
					public const string Service = "Service";
					public const string SRMBooking = "SRM Booking";
					public static string ToValue(ServiceItemTypesEnum @enum)
					{
						switch (@enum)
						{
							case ServiceItemTypesEnum.Workflow:
								return Workflow;
							case ServiceItemTypesEnum.Service:
								return Service;
							case ServiceItemTypesEnum.SRMBooking:
								return SRMBooking;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ServiceItemTypesEnum ToEnum(string s)
					{
						switch (s)
						{
							case Workflow:
								return ServiceItemTypesEnum.Workflow;
							case Service:
								return ServiceItemTypesEnum.Service;
							case SRMBooking:
								return ServiceItemTypesEnum.SRMBooking;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ServiceItemTypesEnum
				{
					Workflow,
					Service,
					SRMBooking
				}

				public static class Serviceorderpriority
				{
					public const string High = "High";
					public const string Medium = "Medium";
					public const string Low = "Low";
					public static string ToValue(ServiceOrderPriorityEnum @enum)
					{
						switch (@enum)
						{
							case ServiceOrderPriorityEnum.High:
								return High;
							case ServiceOrderPriorityEnum.Medium:
								return Medium;
							case ServiceOrderPriorityEnum.Low:
								return Low;
							default:
								throw new ArgumentOutOfRangeException(nameof(@enum), @enum, "Invalid value.");
						}
					}

					public static ServiceOrderPriorityEnum ToEnum(string s)
					{
						switch (s)
						{
							case High:
								return ServiceOrderPriorityEnum.High;
							case Medium:
								return ServiceOrderPriorityEnum.Medium;
							case Low:
								return ServiceOrderPriorityEnum.Low;
							default:
								throw new ArgumentOutOfRangeException(nameof(s), s, "Invalid value.");
						}
					}
				}

				public enum ServiceOrderPriorityEnum
				{
					High,
					Medium,
					Low
				}
			}

			public static class Sections
			{
				public static class ServiceProfile
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("ffb3508a-aaac-4312-bf6d-c64c5f9cd0a0"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ProfileDefinition
					{
						get;
					}

					= new FieldDescriptorID(new Guid("16babe47-3283-41de-9173-fb55cdbd2528"));
					public static FieldDescriptorID Profile
					{
						get;
					}

					= new FieldDescriptorID(new Guid("a163544f-d48a-42fe-916e-5f41a9f3d15e"));
					public static FieldDescriptorID MandatoryAtServiceLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("db86889b-7a2a-4c7f-b617-7b6f9334f850"));
				}

				public static class ServiceItemConfigurationValue
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("7c442399-fc00-4bd0-ac91-705ed3afc606"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ConfigurationParameterValue
					{
						get;
					}

					= new FieldDescriptorID(new Guid("64fef9b2-61da-44b1-8a98-1a73008ffce7"));
					public static FieldDescriptorID WorkflowParamterReference
					{
						get;
					}

					= new FieldDescriptorID(new Guid("dc9f7ae5-8f95-4100-ad49-8053f9bc35e8"));
				}

				public static class ServiceItemRelationship
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("e1ccbd9b-fffb-448f-a6c5-de47e842be9b"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("c42c343d-f8b5-4fe6-a55b-18076b91c5fe"));
					public static FieldDescriptorID Type
					{
						get;
					}

					= new FieldDescriptorID(new Guid("0b00add5-1d5d-41b5-a3f9-98bb8219085b"));
					public static FieldDescriptorID ParentServiceItem
					{
						get;
					}

					= new FieldDescriptorID(new Guid("33c36905-b227-4fcd-8866-a523c61fd5d9"));
					public static FieldDescriptorID ChildServiceItem
					{
						get;
					}

					= new FieldDescriptorID(new Guid("32a96c4e-7553-464a-822b-b8ab2620bfef"));
					public static FieldDescriptorID ParentServiceItemInterfaceID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("f205a562-cbb7-416c-a04d-dd0d99e90d1a"));
					public static FieldDescriptorID ChildServiceItemInterfaceID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("2c4ba097-9481-41e9-bf03-8bee166fc589"));
				}

				public static class ServiceOrderItemConfigurationValue
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("d53e7212-cddd-4594-b073-234a2b6c0e3f"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ConfigurationParameterValue
					{
						get;
					}

					= new FieldDescriptorID(new Guid("f4c875fd-640b-4fc1-a60a-1edb52faf3b2"));
					public static FieldDescriptorID MandatoryAtServiceOrderLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("81e5f226-1e25-4702-927a-7ea2985e19e1"));
				}

				public static class ServiceConfigurationValue
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("b80c6b82-173f-485a-9b9c-328104d343ae"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ConfigurationParameterValue
					{
						get;
					}

					= new FieldDescriptorID(new Guid("ef8d17a3-cb49-44ab-ac8d-8c1652de1e0b"));
					public static FieldDescriptorID MandatoryAtServiceLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("c1d5e2a0-668a-41bc-a58d-455497fe0f61"));
				}

				public static class ServiceConfigurationInfo
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("f91f1783-75c4-447b-a82c-76150902a33d"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID VersionName
					{
						get;
					}

					= new FieldDescriptorID(new Guid("e91a0f81-0c37-48e5-a00a-5f4d35dcfa10"));
					public static FieldDescriptorID Description
					{
						get;
					}

					= new FieldDescriptorID(new Guid("8e980d78-0ef6-4fc7-b8e2-eb358b8e9ff1"));
					public static FieldDescriptorID PreviousVersion
					{
						get;
					}

					= new FieldDescriptorID(new Guid("be86b7a0-2082-420d-ac81-592078828a49"));
					public static FieldDescriptorID StartDate
					{
						get;
					}

					= new FieldDescriptorID(new Guid("b895b58b-ad12-4cff-90db-96b6112eb539"));
					public static FieldDescriptorID EndDate
					{
						get;
					}

					= new FieldDescriptorID(new Guid("6aee6542-02b2-4c2a-b456-430c4b3c605e"));
					public static FieldDescriptorID ServiceConfigurationParameters
					{
						get;
					}

					= new FieldDescriptorID(new Guid("42065bc1-c086-46a8-baf4-714c08f9b714"));
					public static FieldDescriptorID ServiceProfiles
					{
						get;
					}

					= new FieldDescriptorID(new Guid("6a6e5360-dc29-4e16-9874-d56a584df9e0"));
					public static FieldDescriptorID CreatedAt
					{
						get;
					}

					= new FieldDescriptorID(new Guid("45567fe4-81ba-408b-bc6f-5c34351eb3da"));
				}

				public static class ServiceItems
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("1ac7e347-20e5-4b2b-8838-5cb412e89427"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID Label
					{
						get;
					}

					= new FieldDescriptorID(new Guid("24eeee19-8bef-44dc-be82-ef6c538d0f8d"));
					public static FieldDescriptorID ServiceItemID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("01c36e03-5baf-44f9-8bbb-f1e7383cc148"));
					public static FieldDescriptorID ServiceItemType
					{
						get;
					}

					= new FieldDescriptorID(new Guid("8b3e1590-2eeb-4c2c-b249-dd61023a1b06"));
					public static FieldDescriptorID DefinitionReference
					{
						get;
					}

					= new FieldDescriptorID(new Guid("30c7c421-7c97-4723-91e1-046ba1792ec8"));
					public static FieldDescriptorID ServiceItemScript
					{
						get;
					}

					= new FieldDescriptorID(new Guid("bfc7a72c-5e0d-4ffe-9c96-27f5e749d3fa"));
					public static FieldDescriptorID ImplementationReference
					{
						get;
					}

					= new FieldDescriptorID(new Guid("8cedc78a-a23f-46c4-92a3-30393704f340"));
					public static FieldDescriptorID Icon
					{
						get;
					}

					= new FieldDescriptorID(new Guid("9b0fdbce-8ecc-4480-afc0-42010e8e7a69"));
				}

				public static class ServiceSpecificationsProfile
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("78212f45-e9f1-44a1-80ad-be43dd19e21e"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ProfileDefinition
					{
						get;
					}

					= new FieldDescriptorID(new Guid("21c0e5be-6dcf-443c-a5b8-3acf84a445dd"));
					public static FieldDescriptorID Profile
					{
						get;
					}

					= new FieldDescriptorID(new Guid("25e8b1c8-5ab5-43b3-9426-73be75a3bd3c"));
					public static FieldDescriptorID MandatoryAtServiceLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("b0abd6d1-f27b-43c2-ab0a-e7807fdda8da"));
					public static FieldDescriptorID ExposeAtServiceOrderLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("c8bf92f5-c9aa-4793-9633-bc2f38ea1b31"));
					public static FieldDescriptorID MandatoryAtServiceOrderLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("9707e78b-75c5-46b5-a7e5-ad9f122faac6"));
				}

				public static class ServiceOrderItemInfo
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("48b18c79-a682-4dc0-a60f-6986d181e987"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID Name
					{
						get;
					}

					= new FieldDescriptorID(new Guid("34985cc6-5a53-4b84-a8d9-757bd8755a3b"));
					public static FieldDescriptorID Action
					{
						get;
					}

					= new FieldDescriptorID(new Guid("27d6d8bc-fe39-48f5-873f-4a7386c8f250"));
					public static FieldDescriptorID ServiceStartTime
					{
						get;
					}

					= new FieldDescriptorID(new Guid("0b97d054-a8a9-4bda-87be-0a057c74c6f2"));
					public static FieldDescriptorID ServiceEndTime
					{
						get;
					}

					= new FieldDescriptorID(new Guid("9042ad90-787d-4dfa-9943-4a7438f8664d"));
					public static FieldDescriptorID ServiceIndefiniteRuntime
					{
						get;
					}

					= new FieldDescriptorID(new Guid("61bac74e-c192-42a9-981f-a25971e4285e"));
				}

				public static class ServiceSpecificationInfo
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("42fa2357-bed3-4456-b2d2-9a2b8f61fbab"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID SpecificationName
					{
						get;
					}

					= new FieldDescriptorID(new Guid("08908eda-eb78-4d7f-a462-71769da596a3"));
					public static FieldDescriptorID Icon
					{
						get;
					}

					= new FieldDescriptorID(new Guid("7a60d6b5-c37f-4250-810f-b62a501892b9"));
					public static FieldDescriptorID Description
					{
						get;
					}

					= new FieldDescriptorID(new Guid("ee3f4719-8930-476a-b91a-ef98476fb170"));
					public static FieldDescriptorID ServiceSpecificationConfigurationParameters
					{
						get;
					}

					= new FieldDescriptorID(new Guid("62f7f7af-8452-46da-9f3d-4efd0f5d8b9a"));
					public static FieldDescriptorID ServiceSpecificationsProfiles
					{
						get;
					}

					= new FieldDescriptorID(new Guid("7038079c-a9ef-4f0b-8f43-798460315d7f"));
				}

				public static class ServiceOrderItems
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("b9041ff9-4f7f-4412-822f-18c218a5444d"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ServiceOrderItem
					{
						get;
					}

					= new FieldDescriptorID(new Guid("853d9a8c-09e3-4e75-b270-5ebf827e9bdf"));
					public static FieldDescriptorID PriorityOrder
					{
						get;
					}

					= new FieldDescriptorID(new Guid("cad2201c-8663-4656-b53e-91babb984567"));
				}

				public static class ServiceInfo
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("fd700f84-430c-4626-af7e-052d93b89323"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ServiceName
					{
						get;
					}

					= new FieldDescriptorID(new Guid("7a8c2a26-016d-4067-bf60-7b2ff07157cb"));
					public static FieldDescriptorID Description
					{
						get;
					}

					= new FieldDescriptorID(new Guid("5e5f1745-5888-494f-8d7a-da9cdb7bc07f"));
					public static FieldDescriptorID ServiceStartTime
					{
						get;
					}

					= new FieldDescriptorID(new Guid("c3b2346e-f383-4420-85e1-107457ed4137"));
					public static FieldDescriptorID ServiceEndTime
					{
						get;
					}

					= new FieldDescriptorID(new Guid("a1f0a928-fe05-4f47-bbde-e3f88d5ffb6b"));
					public static FieldDescriptorID Icon
					{
						get;
					}

					= new FieldDescriptorID(new Guid("bbb840cf-045f-4581-9103-c0ed696e4f08"));
					public static FieldDescriptorID ServiceSpecifcation
					{
						get;
					}

					= new FieldDescriptorID(new Guid("20003807-2368-456f-b1ad-c8eb2e5c98e9"));
					public static FieldDescriptorID RelatedOrganization
					{
						get;
					}

					= new FieldDescriptorID(new Guid("d0f0ea83-ce6f-4c5d-be6a-f30387a4a703"));
					public static FieldDescriptorID ServiceCategory
					{
						get;
					}

					= new FieldDescriptorID(new Guid("1aba841d-3c8e-411d-9821-a9209c02e4c8"));
					public static FieldDescriptorID ServiceID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("17e449be-c41e-40d1-8844-a43c0d71119f"));
					public static FieldDescriptorID GenerateMonitoringService
					{
						get;
					}

					= new FieldDescriptorID(new Guid("89647ce1-e618-49bd-a711-9feaf5b0f85e"));
					public static FieldDescriptorID ServiceConfiguration
					{
						get;
					}

					= new FieldDescriptorID(new Guid("f50b9d0a-009c-4ce5-bc08-5188784d7994"));
					public static FieldDescriptorID ConfigurationVersions
					{
						get;
					}

					= new FieldDescriptorID(new Guid("2aafde72-b16e-4b66-9a80-fbd85655ad45"));
				}

				public static class ServiceConfigurationParametersValues
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("e1265675-b4a0-48ac-b19d-72ed90ed32e7"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID Label
					{
						get;
					}

					= new FieldDescriptorID(new Guid("a8b810db-407f-49ff-8adf-82bfa6ffc624"));
					public static FieldDescriptorID ServiceParameterID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("12c3d339-d108-4b69-8f16-55e603c11749"));
					public static FieldDescriptorID ProfileParameterID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("119eba63-7d1d-48cc-af12-eb8b07d58a93"));
					public static FieldDescriptorID Mandatory
					{
						get;
					}

					= new FieldDescriptorID(new Guid("ed22bde7-b7d6-4687-b45b-711080d67913"));
					public static FieldDescriptorID StringValue
					{
						get;
					}

					= new FieldDescriptorID(new Guid("3e2a95b2-84a2-4993-ad8d-4ab2fa268437"));
					public static FieldDescriptorID DoubleValue
					{
						get;
					}

					= new FieldDescriptorID(new Guid("0e6868b5-caaa-44bf-b4ba-00fb03f2f0b0"));
				}

				public static class ServiceCategoryInfo
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("8a0d1812-2749-48b9-b673-3bc35c660976"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID Name
					{
						get;
					}

					= new FieldDescriptorID(new Guid("797eeb46-c5fa-4461-aa30-5c83f0a997ee"));
					public static FieldDescriptorID Type
					{
						get;
					}

					= new FieldDescriptorID(new Guid("dc3a4293-a40a-483f-80a8-1f337474d244"));
					public static FieldDescriptorID Icon
					{
						get;
					}

					= new FieldDescriptorID(new Guid("ca45e379-91dd-42db-a06d-f09588aadd7f"));
				}

				public static class ServiceOrderItemServiceInfo
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("4501adfb-7c9f-423c-b449-73a46d32a46b"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ServiceCategory
					{
						get;
					}

					= new FieldDescriptorID(new Guid("50d5611c-e27b-45a3-8767-d3140b101382"));
					public static FieldDescriptorID ServiceSpecification
					{
						get;
					}

					= new FieldDescriptorID(new Guid("951f4359-97bf-4d90-b4ca-7fb3eab51aa1"));
					public static FieldDescriptorID Service
					{
						get;
					}

					= new FieldDescriptorID(new Guid("cd7a33ff-d5f2-40de-910d-616a6e9b3ce2"));
					public static FieldDescriptorID ServiceOrderItemConfigurations
					{
						get;
					}

					= new FieldDescriptorID(new Guid("d97aa318-daf2-4085-ac3f-991e53e2952d"));
				}

				public static class ServiceSpecificationConfigurationValue
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("a4e2826c-f334-4b1e-9704-162c6fd5f2ec"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID ConfigurationParameterValue
					{
						get;
					}

					= new FieldDescriptorID(new Guid("92fda825-193c-4380-962e-86aa7c61f7f0"));
					public static FieldDescriptorID MandatoryAtServiceLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("ac2649ef-e73e-4252-a577-2d0ad083d21b"));
					public static FieldDescriptorID ExposeAtServiceOrderLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("7c991cd6-08e9-4d78-8a55-457e9d3ffa18"));
					public static FieldDescriptorID MandatoryAtServiceOrderLevel
					{
						get;
					}

					= new FieldDescriptorID(new Guid("94cacd16-7b27-4f57-a8fe-669c79d8268e"));
				}

				public static class ServiceOrderInfo
				{
					public static SectionDefinitionID Id
					{
						get;
					}

					= new SectionDefinitionID(new Guid("c8811d15-3006-4478-a29f-f286fb935b46"))
					{ ModuleId = "(slc)servicemanagement" };
					public static FieldDescriptorID Name
					{
						get;
					}

					= new FieldDescriptorID(new Guid("ba13799a-c9b9-4f08-b825-cac8a487af6f"));
					public static FieldDescriptorID ID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("992825d2-778e-4f5f-8fb3-6429f032bdf9"));
					public static FieldDescriptorID ExternalID
					{
						get;
					}

					= new FieldDescriptorID(new Guid("7abc051c-c694-4c06-8860-2e650af11eea"));
					public static FieldDescriptorID Priority
					{
						get;
					}

					= new FieldDescriptorID(new Guid("3b0a1b22-9379-4d52-9eae-5308b5c7577f"));
					public static FieldDescriptorID Description
					{
						get;
					}

					= new FieldDescriptorID(new Guid("40fb0b38-0686-4e77-8e77-1a4c36c0e96c"));
					public static FieldDescriptorID RelatedOrganization
					{
						get;
					}

					= new FieldDescriptorID(new Guid("b071ee6f-9a3f-44c9-a187-3a1a78a37a99"));
					public static FieldDescriptorID OrderContact
					{
						get;
					}

					= new FieldDescriptorID(new Guid("eeeca81e-fc47-44dd-b089-05e61b324b37"));
				}
			}

			public static class Definitions
			{
				public static DomDefinitionId ServiceOrderItemConfigurationValue
				{
					get;
				}

				= new DomDefinitionId(new Guid("5db8a463-780c-443a-83d5-5ea065057637"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceSpecificationConfigurationValue
				{
					get;
				}

				= new DomDefinitionId(new Guid("9732ab35-6469-49e8-908a-6da5624224ab"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceSpecifications
				{
					get;
				}

				= new DomDefinitionId(new Guid("dbe96de4-ca9d-4eba-a06e-b089ec14ffca"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceConfigurationVersion
				{
					get;
				}

				= new DomDefinitionId(new Guid("42e3f398-b966-41fa-96c7-a7a0189f0aab"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceCategory
				{
					get;
				}

				= new DomDefinitionId(new Guid("aa627d77-d73e-4657-8d26-0970371acb9e"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceOrderItems
				{
					get;
				}

				= new DomDefinitionId(new Guid("1480b788-4aff-4e2a-9ee0-ec55bb0f8912"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceOrders
				{
					get;
				}

				= new DomDefinitionId(new Guid("6f8233c7-114a-47c1-b0c8-8573f0a848b5"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId Services
				{
					get;
				}

				= new DomDefinitionId(new Guid("d50bac89-6629-4f3b-aff0-05a57cb7e70d"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceConfiguration
				{
					get;
				}

				= new DomDefinitionId(new Guid("f384fc4f-708b-46a1-9474-bf9fbbe358a7"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceSpecificationProfile
				{
					get;
				}

				= new DomDefinitionId(new Guid("3f872685-8bf7-4f59-80f8-6d21916d1f97"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceConfigurationValue
				{
					get;
				}

				= new DomDefinitionId(new Guid("44a7ac35-c686-4312-9fcd-400ab80e38dd"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceItemConfigurationValue
				{
					get;
				}

				= new DomDefinitionId(new Guid("ef207e58-c0a9-4898-ab99-d59b5fe1ba61"))
				{ ModuleId = "(slc)servicemanagement" };
				public static DomDefinitionId ServiceProfile
				{
					get;
				}

				= new DomDefinitionId(new Guid("b3c7ef51-4f9a-44c1-9572-b8641c47f2b3"))
				{ ModuleId = "(slc)servicemanagement" };
			}

			public static class Behaviors
			{
				public static class Serviceorder_Behavior
				{
					public static DomBehaviorDefinitionId Id
					{
						get;
					}

					= new DomBehaviorDefinitionId(new Guid("9548dac2-dbef-4d14-b319-c608ed7c6ad8"))
					{ ModuleId = "(slc)servicemanagement" };
					public static class Statuses
					{
						public const string New = "06df5562-cd9b-4b0b-bd45-c58560a8b22a";
						public const string Acknowledged = "d917fc53-2638-4ab9-9ac6-651ec5312bac";
						public const string InProgress = "331dc1c2-1950-4c00-a4ae-0aba674a30e6";
						public const string Completed = "260a7073-e54e-4482-a8a7-2b4f2e49c42e";
						public const string Rejected = "6a01a480-4c38-4db7-b545-72ba05742a7e";
						public const string Failed = "7f13d019-29de-43cb-a510-ab2b2a77e785";
						public const string PartiallyFailed = "f8a8d853-faaf-401c-9865-71e314614023";
						public const string Held = "310ea9e9-f65c-4e11-8b1b-e2c34688ef44";
						public const string Pending = "23f9fa75-32b8-4e4a-bd65-06a7344d1902";
						public const string AssessCancellation = "f7e93ddd-cddf-4755-a3e5-0f6ff885dcf5";
						public const string PendingCancellation = "15d08c01-fe63-4d5f-8544-e5b4d66439f5";
						public const string Cancelled = "61b80d48-d555-462e-baae-a52b17c85ddb";
					}

					public static class Transitions
					{
						public const string New_To_Acknowledged = "new_to_acknowledged";
						public const string New_To_Rejected = "new_to_rejected";
						public const string Acknowledged_To_Rejected = "acknowledged_to_rejected";
						public const string Acknowledged_To_Inprogress = "acknowledged_to_inprogress";
						public const string Inprogress_To_Completed = "inprogress_to_completed";
						public const string Inprogress_To_Failed = "inprogress_to_failed";
						public const string Inprogress_To_Partial = "inprogress_to_partial";
						public const string Inprogress_To_Held = "inprogress_to_held";
						public const string Inprogress_To_Pending = "inprogress_to_pending";
						public const string Pending_To_Assesscancellation = "pending_to_assesscancellation";
						public const string Assesscancellation_To_Pendingcancellation = "assesscancellation_to_pendingcancellation";
						public const string Pendingcancellation_To_Cancelled = "pendingcancellation_to_cancelled";
						public const string Held_To_Inprogress = "held_to_inprogress";
						public const string Assesscancellation_To_Held = "assesscancellation_to_held";
						public const string Assesscancellation_To_Pending = "assesscancellation_to_pending";
						public const string Held_To_Assesscancellation = "held_to_assesscancellation";
						public const string Pending_To_Inprogress = "pending_to_inprogress";
					}
				}

				public static class Serviceorderitem_Behavior
				{
					public static DomBehaviorDefinitionId Id
					{
						get;
					}

					= new DomBehaviorDefinitionId(new Guid("9e644aab-6b60-4cce-a901-520162077080"))
					{ ModuleId = "(slc)servicemanagement" };
					public static class Statuses
					{
						public const string New = "06df5562-cd9b-4b0b-bd45-c58560a8b22a";
						public const string Acknowledged = "d917fc53-2638-4ab9-9ac6-651ec5312bac";
						public const string InProgress = "331dc1c2-1950-4c00-a4ae-0aba674a30e6";
						public const string Completed = "260a7073-e54e-4482-a8a7-2b4f2e49c42e";
						public const string Rejected = "6a01a480-4c38-4db7-b545-72ba05742a7e";
						public const string Failed = "7f13d019-29de-43cb-a510-ab2b2a77e785";
						public const string PartiallyFailed = "f8a8d853-faaf-401c-9865-71e314614023";
						public const string Held = "310ea9e9-f65c-4e11-8b1b-e2c34688ef44";
						public const string Pending = "23f9fa75-32b8-4e4a-bd65-06a7344d1902";
						public const string AssessCancellation = "f7e93ddd-cddf-4755-a3e5-0f6ff885dcf5";
						public const string PendingCancellation = "15d08c01-fe63-4d5f-8544-e5b4d66439f5";
						public const string Cancelled = "61b80d48-d555-462e-baae-a52b17c85ddb";
					}

					public static class Transitions
					{
						public const string New_To_Acknowledged = "new_to_acknowledged";
						public const string New_To_Rejected = "new_to_rejected";
						public const string Acknowledged_To_Rejected = "acknowledged_to_rejected";
						public const string Acknowledged_To_Inprogress = "acknowledged_to_inprogress";
						public const string Inprogress_To_Completed = "inprogress_to_completed";
						public const string Inprogress_To_Failed = "inprogress_to_failed";
						public const string Inprogress_To_Partial = "inprogress_to_partial";
						public const string Inprogress_To_Held = "inprogress_to_held";
						public const string Inprogress_To_Pending = "inprogress_to_pending";
						public const string Pending_To_Assesscancellation = "pending_to_assesscancellation";
						public const string Assesscancellation_To_Pendingcancellation = "assesscancellation_to_pendingcancellation";
						public const string Pendingcancellation_To_Cancelled = "pendingcancellation_to_cancelled";
						public const string Held_To_Inprogress = "held_to_inprogress";
						public const string Assesscancellation_To_Held = "assesscancellation_to_held";
						public const string Assesscancellation_To_Pending = "assesscancellation_to_pending";
						public const string Held_To_Assesscancellation = "held_to_assesscancellation";
						public const string Pending_To_Inprogress = "pending_to_inprogress";
					}
				}

				public static class Service_Behavior
				{
					public static DomBehaviorDefinitionId Id
					{
						get;
					}

					= new DomBehaviorDefinitionId(new Guid("b9fad406-ebce-47c0-8620-c1d3679279ee"))
					{ ModuleId = "(slc)servicemanagement" };
					public static class Statuses
					{
						public const string New = "d7b94689-2565-48b2-8291-92bf9fc43498";
						public const string Designed = "51d496fc-2596-4fcc-aca0-4fb5e4f7d211";
						public const string Reserved = "51d496fc-2596-4fcc-aca0-4fb5e4f7d211 (duplicate)";
						public const string Active = "51d496fc-2596-4fcc-aca0-4fb5e4f7d211 (duplicate) (duplicate)";
						public const string Terminated = "701ce0f7-637c-4c86-a807-d36fe499649c";
						public const string Retired = "21923bba-4019-404f-bfb2-b32abd2de748";
					}

					public static class Transitions
					{
						public const string New_To_Designed = "new_to_designed";
						public const string Designed_To_Reserved = "designed_to_reserved";
						public const string Reserved_To_Active = "reserved_to_active";
						public const string Active_To_Terminated = "active_to_terminated";
						public const string Terminated_To_Retired = "terminated_to_retired";
						public const string New_To_Retired = "new_to_retired";
						public const string Designed_To_Retired = "designed_to_retired";
						public const string Reserved_To_Retired = "reserved_to_retired";
						public const string Terminated_To_Active = "terminated_to_active";
					}
				}
			}
		}
	}
}
